### ISSUE TITLE
Add question metadata

### ISSUE THREAD

**Issue by subinasr** [the-deep/qber-backend#20]
### Screenshot
![Image](https://github.com/the-deep/qber-backend/assets/51225380/1a4dab7d-f828-4850-9a60-643db9e999e2)

### [Excel Spreadsheet](https://docs.google.com/spreadsheets/d/1-TixKO8YqBQC4daqKVWIAF4d1cKdB7on/edit#gid=232537286)

# Task list
- [x] Add new fields in the database
- [x] Add new fields in the Query
- [x] Add new fields in the Mutation
